# -*- coding: utf-8 -*-
"""Lab Experiment - 6  Vishwa V (192421374).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvOlltpcSIyg0YfIPrB1q1tIoqsigwDR
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score


iris = load_iris()
X = iris.data
y = iris.target


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
    )


model = GaussianNB()


model.fit(X_train, y_train)


y_pred = model.predict(X_test)


print("Actual Values:")
print(y_test)

print("\nPredicted Values:")
print(y_pred)


cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)


accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy: {:.2f}%".format(accuracy * 100))