# -*- coding: utf-8 -*-
"""Vishwa V (192421374) Lab Experiment - 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mkxsx9sc7zrmqL6E0EojehFbzG8aaBYp
"""

import csv

with open('/trainingdata.csv', 'r') as file:
    data = list(csv.reader(file))

    data = data[1:]

    concepts = [row[:-1] for row in data]
    target = [row[-1] for row in data]

    specific_h = concepts[0].copy()

    general_h = [['?' for _ in range(len(specific_h))] for _ in range(len(specific_h))]

    print("Initial Specific Hypothesis:")
    print(specific_h)

    print("\nInitial General Hypothesis:")
    for row_g in general_h:
        print(row_g)

    for i, h in enumerate(concepts):
        if target[i] == "Yes":
            for x in range(len(specific_h)):
                if h[x] != specific_h[x]:
                    specific_h[x] = '?'
                    # This line's logic (general_h[x][x] = '?') might need review for standard CE
                    # as it only updates diagonal elements of general_h.
                    # For now, it's kept as per original user's intent after indentation fix.
                    general_h[x][x] = '?'

        elif target[i] == "No":
            for x in range(len(specific_h)):
                if h[x] != specific_h[x]:
                    # This line's logic might need review for standard CE.
                    general_h[x][x] = specific_h[x]
                else:
                    # This line's logic might need review for standard CE.
                    general_h[x][x] = '?'

    print("\nFinal Specific Hypothesis:")
    print(specific_h)

    print("\nFinal General Hypothesis:")
    # Filter out rows that are entirely '?' if that's the intention
    # The original condition `row != ['?', '?', '?', '?', '?', '?']` assumes a fixed length.
    # Using a dynamically generated list of '?' for comparison.
    all_q_row = ['?'] * len(specific_h)
    found_non_specific_general_h = False
    for row_g in general_h:
        if row_g != all_q_row:
            print(row_g)
            found_non_specific_general_h = True
    if not found_non_specific_general_h:
        print("No non-specific general hypotheses found.")