# -*- coding: utf-8 -*-
"""Copy of Vishwa V (192421374) Lab Experiment - 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1980OG-s7Q96yPszrLTP22HxLN3i3zCfv
"""

import csv

with open('/trainingdata.csv', 'r') as file:
    data = list(csv.reader(file))

    data = data[1:]

    num_attributes = len(data[0]) - 1

    hypothesis = ['0'] * num_attributes

    for row in data:
        if row[-1] == "Yes":
            for i in range(num_attributes):
                if hypothesis[i] == '0':
                    hypothesis[i] = row[i]
                elif hypothesis[i] != row[i]:
                    hypothesis[i] = '?'
            # Print hypothesis after processing each 'Yes' example
            print(hypothesis)

    # Print the final hypothesis after all training examples
    print("\nFinal Hypothesis:")
    print(hypothesis)